name: TF Plan Comment
on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

permissions:
  issues: write
  pull-requests: write
  id-token: write

jobs:
  plan-comment:
    runs-on: ubuntu-latest
    environment:
      name: tfauto
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 #v2.27.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: terraform-plan.yaml
          run_id: ${{ github.event.workflow_run.id }}
      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b #v1.1.6
        with:
          path: ./pr_num/pr_num.txt
      - name: Remove new line characters
        run: echo "PR_NUM=$(echo '${{ steps.pr_num_reader.outputs.content }}' | tr -d '\n')" >> $GITHUB_ENV
      - name: Checkout
        if: env.PR_NUM != ''
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Azure login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Download pr tfplan
        if: env.PR_NUM != ''
        run: |
          az storage blob download --account-name avmtelemetrystate --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{ env.PR_NUM }}.txt --no-progress --file tfplan.txt --auth-mode login
      - name: Read Terraform version
        if: env.PR_NUM != ''
        id: read_version
        run: echo "TF_VERSION=$(head -n 1 tfplan.txt)" >> $GITHUB_ENV
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        if: env.PR_NUM != ''
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup Terragrunt
        if: env.PR_NUM != ''
        uses: autero1/action-terragrunt@22b4647f1263865cda4473831640e71d349db2cd # 1.3.2
        with:
          terragrunt_version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Init
        if: env.PR_NUM != ''
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_USE_OIDC: "true"
        run: |
          export ARM_OIDC_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
          export ARM_OIDC_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL
          sh scripts/terragrunt-init.sh
          echo '=========> Existing resources:' > output
          terragrunt state list | tee -a output
          cat tfplan.txt | tee -a output
      - name: Show Terraform Plan
        if: env.PR_NUM != ''
        id: tfshow
        uses: mathiasvr/command-output@34408ea3d0528273faff3d9e201761ae96106cd0 # 2.0.0
        with:
          run: cat output
      - name: PR comment with reactions
        if: env.PR_NUM != ''
        uses: thollander/actions-comment-pull-request@8a3fad13c20088e9eb0805666b9fe49509d2fec8 # 1.6.0
        with:
          message: |
            ```
            ${{ steps.tfshow.outputs.stdout }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ env.PR_NUM }}